# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\x04\x63hat\"\x1f\n\x0bJoinRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"-\n\x0b\x43hatMessage\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\"\x07\n\x05\x45mpty2p\n\x0b\x43hatService\x12\x32\n\x08JoinChat\x12\x11.chat.JoinRequest\x1a\x11.chat.ChatMessage0\x01\x12-\n\x0bSendMessage\x12\x11.chat.ChatMessage\x1a\x0b.chat.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_JOINREQUEST']._serialized_start=20
  _globals['_JOINREQUEST']._serialized_end=51
  _globals['_CHATMESSAGE']._serialized_start=53
  _globals['_CHATMESSAGE']._serialized_end=98
  _globals['_EMPTY']._serialized_start=100
  _globals['_EMPTY']._serialized_end=107
  _globals['_CHATSERVICE']._serialized_start=109
  _globals['_CHATSERVICE']._serialized_end=221
# @@protoc_insertion_point(module_scope)
